### PR TITLE
Fix eslint issues

### PR DESCRIPTION
**Pull request by iagodahlem**
- add eslint config

### CODE REVIEW

**Comment by fladson** [comment]
I need FE help to fix the affected specs.

```
TOTAL: 2 FAILED, 313 SUCCESS


1) binds setFakeClass to change:userVelocity on the model
     ProjectVelocityView initialize
     Expected spy "stub" to have been called with [ 'change:userVelocity', Function ]
webpack:///spec/javascripts/views/project_velocity_view_spec.js:38:8 <- /Users/fladson/Documents/code/cm42-central/spec/javascripts/index.js:224633:50

2) binds render to rebuilt-iterations on the model
     ProjectVelocityView initialize
     Expected spy "stub" to have been called with [ 'rebuilt-iterations', Function ]
webpack:///spec/javascripts/views/project_velocity_view_spec.js:44:8 <- /Users/fladson/Documents/code/cm42-central/spec/javascripts/index.js:224641:50
```

**Comment by fladson** [comment]
not sure why codeclimate is showing **61 issues to fix**, locally I am getting
```
✖ 61 problems (0 errors, 61 warnings)
```

**Comment by fladson** [comment]
@adbatista can we ignore the warnings?

**Comment by talyssonoc** [comment]
@fladson You can change this:

https://github.com/Codeminer42/cm42-central/blob/master/spec/javascripts/views/project_velocity_view_spec.js#L7

to this:

```js
this.model = {};
```
---

After this line: https://github.com/Codeminer42/cm42-central/blob/master/spec/javascripts/views/project_velocity_view_spec.js#L19

add this:

```js
this.subject.listenTo = sinon.stub();
```
---
this:

https://github.com/Codeminer42/cm42-central/blob/master/spec/javascripts/views/project_velocity_view_spec.js#L37-L39

to this:

```js
expect(this.subject.listenTo).toHaveBeenCalledWith(
  this.subject.model, "change:userVelocity", this.subject.setFakeClass
);
```

---

and this:

https://github.com/Codeminer42/cm42-central/blob/master/spec/javascripts/views/project_velocity_view_spec.js#L43-L45

to this:

```js
expect(this.subject.listenTo).toHaveBeenCalledWith(
  this.subject.model, "rebuilt-iterations", this.subject.render
);
```

**Comment by fladson** [comment]
Still failing with the suggested changes 😢

**Comment by rjchaveiro** [comment]
Still failing on
```
TOTAL: 2 FAILED, 313 SUCCESS


1) binds setFakeClass to change:userVelocity on the model
     ProjectVelocityView initialize
     Expected spy "stub" to have been called with [ 'change:userVelocity', Function ]
webpack:///spec/javascripts/views/project_velocity_view_spec.js:38:8 <- /Users/fladson/Documents/code/cm42-central/spec/javascripts/index.js:224633:50

2) binds render to rebuilt-iterations on the model
     ProjectVelocityView initialize
     Expected spy "stub" to have been called with [ 'rebuilt-iterations', Function ]
webpack:///spec/javascripts/views/project_velocity_view_spec.js:44:8 <- /Users/fladson/Documents/code/cm42-central/spec/javascripts/index.js:224641:50
```
After many attempts to solve that issue.

**Pull request merged**
